import { query } from "@/lib/db";

// Backend-owned, per-module sequential "Spokesperson N" numbering for the TV
// Debate (`debates`) and Press Conference (`press_conferences`) modules.
//
// Rules (see the task spec):
//   • Each record gets the LOWEST available positive integer not used by another
//     record in the SAME table — so gaps left by deletions are reused, and the
//     two modules number independently.
//   • The number is generated by the backend/DB only; any client-supplied value
//     is ignored. Editing a record never changes its number; deleting frees it.
//   • A UNIQUE index guarantees no two rows share a number even under concurrent
//     creates — the loser of a race retries with the next lowest number.
//   • Existing rows are migrated once (assigned deterministic numbers by id
//     order) without renumbering anything that already has a number.
//
// Stored as a plain INTEGER (`spokesperson_number`); the UI renders "Spokesperson N".

const TABLES = new Set(["debates", "press_conferences"]);
const ensured = {}; // per-process, per-table

function assertTable(table) {
  if (!TABLES.has(table)) throw new Error(`spokespersonNumber: unsupported table "${table}"`);
  return table;
}

async function columnExists(table, column) {
  const rows = await query(
    `SELECT COUNT(*) AS n FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? AND COLUMN_NAME = ?`,
    [table, column]
  );
  return Number(rows[0]?.n || 0) > 0;
}
async function indexExists(table, index) {
  const rows = await query(
    `SELECT COUNT(*) AS n FROM information_schema.STATISTICS
      WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? AND INDEX_NAME = ?`,
    [table, index]
  );
  return Number(rows[0]?.n || 0) > 0;
}

// The lowest positive integer not currently used by any row in `table`.
// Candidates are 1 and (each existing number + 1); the smallest candidate that
// is not already taken is the answer — this yields 1 on an empty table and
// correctly fills the lowest gap after deletions.
export async function nextSpokespersonNumber(table) {
  assertTable(table);
  const rows = await query(
    `SELECT MIN(x.num) AS next FROM (
        SELECT 1 AS num
        UNION
        SELECT spokesperson_number + 1 FROM ${table} WHERE spokesperson_number IS NOT NULL
     ) x
     WHERE NOT EXISTS (SELECT 1 FROM ${table} t WHERE t.spokesperson_number = x.num)`
  );
  const n = Number(rows[0]?.next || 1);
  return n > 0 ? n : 1;
}

// One-time migration: assign a number to every row that lacks one, in id order,
// reusing the lowest-available each time (so a partially-numbered table fills its
// gaps). Rows that already have a number are left untouched.
async function migrateMissing(table) {
  const missing = await query(`SELECT id FROM ${table} WHERE spokesperson_number IS NULL ORDER BY id ASC`);
  for (const r of missing) {
    const n = await nextSpokespersonNumber(table);
    try {
      await query(`UPDATE ${table} SET spokesperson_number = ? WHERE id = ?`, [n, r.id]);
    } catch (e) {
      // A concurrent migrator may have taken this number; skip and let the next
      // ensure pass (or the retry loop on create) settle it.
      if (!(e && (e.code === "ER_DUP_ENTRY" || e.errno === 1062))) throw e;
    }
  }
}

// Idempotent: add the column, migrate existing rows, add the UNIQUE index.
export async function ensureSpokespersonNumberSchema(table) {
  assertTable(table);
  if (ensured[table]) return;
  try {
    if (!(await columnExists(table, "spokesperson_number"))) {
      await query(`ALTER TABLE ${table} ADD COLUMN spokesperson_number INT NULL`);
    }
    await migrateMissing(table);
    const idx = `uq_${table}_spokesperson_number`;
    if (!(await indexExists(table, idx))) {
      // UNIQUE across non-NULL values (MySQL allows multiple NULLs). After the
      // migration every row has a number, so this cannot fail on legacy data.
      await query(`ALTER TABLE ${table} ADD UNIQUE INDEX ${idx} (spokesperson_number)`);
    }
    ensured[table] = true;
  } catch (e) {
    console.error(`[spokespersonNumber] ensure ${table}:`, e?.message || e);
  }
}

// Allocate the next number and run `doInsert(number)` to create the row. If a
// concurrent create grabbed the same number (UNIQUE violation), recompute and
// retry. Returns { res, number }. Nothing is written unless a number is secured,
// so a failure never leaves a half-created / mis-numbered record.
export async function createWithSpokespersonNumber(table, doInsert) {
  assertTable(table);
  await ensureSpokespersonNumberSchema(table);
  let lastErr;
  for (let attempt = 0; attempt < 8; attempt++) {
    const number = await nextSpokespersonNumber(table);
    try {
      const res = await doInsert(number);
      return { res, number };
    } catch (e) {
      if (e && (e.code === "ER_DUP_ENTRY" || e.errno === 1062)) { lastErr = e; continue; }
      throw e;
    }
  }
  throw lastErr || new Error("could not allocate a spokesperson number");
}
