import { Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer";
import React from "react";
import { PdfHeader, PDF_HEADER_HEIGHT } from "@/lib/pdf/commonHeader";

// Professional print/export template shared by the PDF export route — org
// header + logo, filters-used summary, generated date/by, page numbers,
// totals, landscape/portrait. This is the "professional printable report"
// half of the redesign; the browser Print view (src/app/dashboard/reports/
// print/page.js) mirrors the same information in HTML/CSS for on-screen
// print-preview, since a PDF download and an in-browser print are different
// user journeys but should look like the same report.

const styles = StyleSheet.create({
  page: { paddingTop: PDF_HEADER_HEIGHT + 12, paddingBottom: 40, paddingHorizontal: 28, fontSize: 8, fontFamily: "Helvetica" },
  header: { flexDirection: "row", alignItems: "center", marginBottom: 10, paddingBottom: 8, borderBottom: 2, borderColor: "#164FA3" },
  logo: { width: 34, height: 34, borderRadius: 17, marginRight: 10 },
  orgName: { fontSize: 13, fontFamily: "Helvetica-Bold", color: "#0B3A82" },
  orgSub: { fontSize: 7.5, color: "#666" },
  title: { fontSize: 14, fontFamily: "Helvetica-Bold", marginTop: 10, marginBottom: 2 },
  metaRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 8 },
  metaText: { fontSize: 7.5, color: "#555" },
  filtersBox: { backgroundColor: "#F4F6FA", borderRadius: 4, padding: 6, marginBottom: 10 },
  filtersLabel: { fontSize: 7, fontFamily: "Helvetica-Bold", color: "#164FA3", marginBottom: 2, textTransform: "uppercase" },
  filterLine: { fontSize: 7.5, color: "#333" },
  row: { flexDirection: "row", borderBottom: 1, borderColor: "#eee", paddingVertical: 4 },
  headerRow: { backgroundColor: "#0B3A82" },
  cell: { paddingHorizontal: 4 },
  cellHeader: { paddingHorizontal: 4, color: "#fff", fontFamily: "Helvetica-Bold" },
  totalsRow: { flexDirection: "row", backgroundColor: "#EEF2FA", paddingVertical: 5, marginTop: 2, borderTop: 1, borderColor: "#164FA3" },
  totalsText: { fontSize: 8, fontFamily: "Helvetica-Bold", color: "#0B3A82", paddingHorizontal: 4 },
  footer: { position: "absolute", bottom: 16, left: 28, right: 28, flexDirection: "row", justifyContent: "space-between", fontSize: 7, color: "#888", borderTop: 1, borderColor: "#eee", paddingTop: 4 },
});

export default function ReportPdfDocument({ title, filterLines, generatedBy, result, orientation }) {
  const generatedAt = new Date().toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });

  return React.createElement(
    Document,
    null,
    React.createElement(
      Page,
      { size: "A4", orientation, style: styles.page },

      // Common fixed header (Arvind Kejriwal Ji photo + party name), on every page.
      React.createElement(PdfHeader, { subtitle: `${title} Report` }),

      React.createElement(Text, { style: styles.title }, `${title} Report`),
      React.createElement(
        View,
        { style: styles.metaRow },
        React.createElement(Text, { style: styles.metaText }, `Generated: ${generatedAt}`),
        React.createElement(Text, { style: styles.metaText }, `Generated by: ${generatedBy}`)
      ),

      filterLines?.length > 0 && React.createElement(
        View,
        { style: styles.filtersBox },
        React.createElement(Text, { style: styles.filtersLabel }, "Filters applied"),
        filterLines.map((line, i) => React.createElement(Text, { key: i, style: styles.filterLine }, line))
      ),

      result.mode === "summary" ? renderSummary(result) : renderDetail(result),

      // Page numbers
      React.createElement(
        View,
        { style: styles.footer, fixed: true },
        React.createElement(Text, null, "Aam Aadmi Party, Chhattisgarh — Reports Center"),
        React.createElement(Text, {
          render: ({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`,
        })
      )
    )
  );
}

function renderSummary(result) {
  const flex = [3, 1];
  return React.createElement(
    View,
    null,
    React.createElement(
      View,
      { style: [styles.row, styles.headerRow] },
      React.createElement(Text, { style: [styles.cellHeader, { flex: flex[0] }] }, result.group_label),
      React.createElement(Text, { style: [styles.cellHeader, { flex: flex[1], textAlign: "right" }] }, "Count")
    ),
    result.rows.map((r, i) =>
      React.createElement(
        View,
        { key: i, style: styles.row, wrap: false },
        React.createElement(Text, { style: [styles.cell, { flex: flex[0] }] }, String(r.group_key ?? "—")),
        React.createElement(Text, { style: [styles.cell, { flex: flex[1], textAlign: "right" }] }, String(r.count))
      )
    ),
    React.createElement(
      View,
      { style: styles.totalsRow },
      React.createElement(Text, { style: [styles.totalsText, { flex: flex[0] }] }, `Total — ${result.rows.length} groups`),
      React.createElement(Text, { style: [styles.totalsText, { flex: flex[1], textAlign: "right" }] }, String(result.rows.reduce((s, r) => s + r.count, 0)))
    )
  );
}

function renderDetail(result) {
  // Zero matching rows → a valid PDF that still shows the header/filters (above)
  // plus a clear "no records" message, instead of an empty/blank page.
  if (!result.rows || result.rows.length === 0) {
    return React.createElement(
      View,
      { style: { padding: 16, alignItems: "center" } },
      React.createElement(Text, { style: { fontSize: 10, color: "#666" } }, "No records found for the selected filters.")
    );
  }
  const flex = result.columns.map(() => 1);
  return React.createElement(
    View,
    null,
    React.createElement(
      View,
      { style: [styles.row, styles.headerRow], fixed: true },
      result.columns.map((c, i) => React.createElement(Text, { key: i, style: [styles.cellHeader, { flex: flex[i] }] }, c.label))
    ),
    result.rows.map((row, i) =>
      React.createElement(
        View,
        { key: i, style: styles.row, wrap: false },
        result.columns.map((c, j) => React.createElement(Text, { key: j, style: [styles.cell, { flex: flex[j] }] }, formatVal(c, row[c.key])))
      )
    ),
    React.createElement(
      View,
      { style: styles.totalsRow },
      React.createElement(
        Text,
        { style: styles.totalsText },
        `Total records: ${result.total}` +
          (result.truncated
            ? ` — this PDF shows the first ${result.rows.length}. Use the Excel or CSV export for the complete dataset.`
            : "")
      )
    )
  );
}

function formatVal(col, v) {
  if (v === null || v === undefined || v === "") return "—";
  if (col.type === "bool") return v == 1 ? "Yes" : "No";
  return String(v);
}
